// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: plbx.proto

package plbxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Policy is the host's egress policy: a preset, plus the rules over it.
type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preset        string                 `protobuf:"bytes,1,opt,name=preset,proto3" json:"preset,omitempty"`
	Rules         []*Rule                `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_plbx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *Policy) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// Rule is one policy entry. Pattern is a host, optionally with a port, and may
// lead with "*." to cover subdomains.
type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Allow         bool                   `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_plbx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{1}
}

func (x *Rule) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Rule) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

// Decision is one thing the proxy let through or refused.
type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Allowed       bool                   `protobuf:"varint,5,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Sandbox       string                 `protobuf:"bytes,7,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_plbx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{2}
}

func (x *Decision) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Decision) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Decision) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Decision) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Decision) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *Decision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Decision) GetSandbox() string {
	if x != nil {
		return x.Sandbox
	}
	return ""
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Ports         []*Port                `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_plbx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{3}
}

func (x *PublishRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *PublishRequest) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_plbx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{4}
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_plbx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{5}
}

type GetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyResponse) Reset() {
	*x = GetPolicyResponse{}
	mi := &file_plbx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyResponse) ProtoMessage() {}

func (x *GetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{6}
}

func (x *GetPolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type SetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPolicyRequest) Reset() {
	*x = SetPolicyRequest{}
	mi := &file_plbx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPolicyRequest) ProtoMessage() {}

func (x *SetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{7}
}

func (x *SetPolicyRequest) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type SetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPolicyResponse) Reset() {
	*x = SetPolicyResponse{}
	mi := &file_plbx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPolicyResponse) ProtoMessage() {}

func (x *SetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{8}
}

type ConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         uint64                 `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionsRequest) Reset() {
	*x = ConnectionsRequest{}
	mi := &file_plbx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionsRequest) ProtoMessage() {}

func (x *ConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionsRequest.ProtoReflect.Descriptor instead.
func (*ConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectionsRequest) GetSince() uint64 {
	if x != nil {
		return x.Since
	}
	return 0
}

type ConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decisions     []*Decision            `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionsResponse) Reset() {
	*x = ConnectionsResponse{}
	mi := &file_plbx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionsResponse) ProtoMessage() {}

func (x *ConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectionsResponse) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

// Spec is what a sandbox's container was built from, fixed when it is created.
type Spec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Workspaces    []*Workspace           `protobuf:"bytes,4,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	Resources     *Resources             `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Clone         bool                   `protobuf:"varint,9,opt,name=clone,proto3" json:"clone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_plbx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{11}
}

func (x *Spec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spec) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Spec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Spec) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *Spec) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Spec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Spec) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Spec) GetClone() bool {
	if x != nil {
		return x.Clone
	}
	return false
}

// Workspace is a host directory bound into the sandbox at its own absolute path.
type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,2,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_plbx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{12}
}

func (x *Workspace) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Workspace) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

// Resources caps a sandbox's consumption. Zero means unlimited.
type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpus          float64                `protobuf:"fixed64,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory        int64                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"` // bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_plbx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{13}
}

func (x *Resources) GetCpus() float64 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *Resources) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

// Port publishes a sandbox port on the host.
type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          int32                  `protobuf:"varint,1,opt,name=host,proto3" json:"host,omitempty"`
	Sandbox       int32                  `protobuf:"varint,2,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Proto         string                 `protobuf:"bytes,3,opt,name=proto,proto3" json:"proto,omitempty"` // "tcp", which is also the default
	Bind          string                 `protobuf:"bytes,4,opt,name=bind,proto3" json:"bind,omitempty"`   // host address; empty is every interface
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_plbx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{14}
}

func (x *Port) GetHost() int32 {
	if x != nil {
		return x.Host
	}
	return 0
}

func (x *Port) GetSandbox() int32 {
	if x != nil {
		return x.Sandbox
	}
	return 0
}

func (x *Port) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *Port) GetBind() string {
	if x != nil {
		return x.Bind
	}
	return ""
}

// State is what plbx last observed about a sandbox.
//
// Status is carried as the string the domain type already uses rather than an
// enum: the store persists these strings, and a mapping table between the two
// spellings is one more thing that can drift.
type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_plbx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{15}
}

func (x *State) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *State) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *State) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *State) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// Sandbox is a stored spec, its observed state, and the ports it publishes.
type Sandbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *Spec                  `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	State         *State                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Ports         []*Port                `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sandbox) Reset() {
	*x = Sandbox{}
	mi := &file_plbx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sandbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sandbox) ProtoMessage() {}

func (x *Sandbox) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sandbox.ProtoReflect.Descriptor instead.
func (*Sandbox) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{16}
}

func (x *Sandbox) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Sandbox) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Sandbox) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

// Ref identifies a sandbox, by name or by a workspace path it was created for.
type Ref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_plbx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{17}
}

func (x *Ref) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ref) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Path names one side of a copy. Sandbox is empty for a host path.
type Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       string                 `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_plbx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{18}
}

func (x *Path) GetSandbox() string {
	if x != nil {
		return x.Sandbox
	}
	return ""
}

func (x *Path) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ExecRequest describes a command to run inside a sandbox.
type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           []string               `protobuf:"bytes,1,rep,name=cmd,proto3" json:"cmd,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workdir       string                 `protobuf:"bytes,3,opt,name=workdir,proto3" json:"workdir,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Interactive   bool                   `protobuf:"varint,5,opt,name=interactive,proto3" json:"interactive,omitempty"` // wire up stdin
	Tty           bool                   `protobuf:"varint,6,opt,name=tty,proto3" json:"tty,omitempty"`                 // allocate a pseudo-terminal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_plbx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{19}
}

func (x *ExecRequest) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *ExecRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ExecRequest) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *ExecRequest) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

// Sample is one reading of a running sandbox's resource use.
type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	MemoryLimit   int64                  `protobuf:"varint,3,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_plbx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{20}
}

func (x *Sample) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Sample) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *Sample) GetMemoryLimit() int64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

// Size is a terminal's dimensions, sent at session start and on every resize.
type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_plbx_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{21}
}

func (x *Size) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Size) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *Spec                  `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_plbx_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{22}
}

func (x *CreateRequest) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *Sandbox               `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_plbx_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{23}
}

func (x *CreateResponse) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_plbx_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{24}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*Sandbox             `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_plbx_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{25}
}

func (x *ListResponse) GetSandboxes() []*Sandbox {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_plbx_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{26}
}

func (x *InspectRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type InspectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *Sandbox               `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_plbx_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{27}
}

func (x *InspectResponse) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_plbx_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{28}
}

func (x *StartRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_plbx_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{29}
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_plbx_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{30}
}

func (x *StopRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_plbx_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{31}
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_plbx_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{32}
}

func (x *RemoveRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *RemoveRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_plbx_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{33}
}

type CopyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *Path                  `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst           *Path                  `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyRequest) Reset() {
	*x = CopyRequest{}
	mi := &file_plbx_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRequest) ProtoMessage() {}

func (x *CopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRequest.ProtoReflect.Descriptor instead.
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{34}
}

func (x *CopyRequest) GetSrc() *Path {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *CopyRequest) GetDst() *Path {
	if x != nil {
		return x.Dst
	}
	return nil
}

type CopyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyResponse) Reset() {
	*x = CopyResponse{}
	mi := &file_plbx_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResponse) ProtoMessage() {}

func (x *CopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResponse.ProtoReflect.Descriptor instead.
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{35}
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_plbx_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{36}
}

func (x *StatsRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

// ExecStart opens a session. It must be the client's first frame.
type ExecStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Request       *ExecRequest           `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Size          *Size                  `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"` // initial dimensions, when the request wants a tty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_plbx_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{37}
}

func (x *ExecStart) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *ExecStart) GetRequest() *ExecRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExecStart) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

// ExecStdinClose signals EOF on stdin without ending the session, so a command
// reading to EOF can finish while its output is still on the way back.
type ExecStdinClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStdinClose) Reset() {
	*x = ExecStdinClose{}
	mi := &file_plbx_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStdinClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStdinClose) ProtoMessage() {}

func (x *ExecStdinClose) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStdinClose.ProtoReflect.Descriptor instead.
func (*ExecStdinClose) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{38}
}

// ExecClientFrame is anything the client sends during a session.
type ExecClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ExecClientFrame_Start
	//	*ExecClientFrame_Stdin
	//	*ExecClientFrame_Resize
	//	*ExecClientFrame_StdinClose
	Frame         isExecClientFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecClientFrame) Reset() {
	*x = ExecClientFrame{}
	mi := &file_plbx_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecClientFrame) ProtoMessage() {}

func (x *ExecClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecClientFrame.ProtoReflect.Descriptor instead.
func (*ExecClientFrame) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{39}
}

func (x *ExecClientFrame) GetFrame() isExecClientFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ExecClientFrame) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Frame.(*ExecClientFrame_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecClientFrame) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Frame.(*ExecClientFrame_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecClientFrame) GetResize() *Size {
	if x != nil {
		if x, ok := x.Frame.(*ExecClientFrame_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ExecClientFrame) GetStdinClose() *ExecStdinClose {
	if x != nil {
		if x, ok := x.Frame.(*ExecClientFrame_StdinClose); ok {
			return x.StdinClose
		}
	}
	return nil
}

type isExecClientFrame_Frame interface {
	isExecClientFrame_Frame()
}

type ExecClientFrame_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecClientFrame_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecClientFrame_Resize struct {
	Resize *Size `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

type ExecClientFrame_StdinClose struct {
	StdinClose *ExecStdinClose `protobuf:"bytes,4,opt,name=stdin_close,json=stdinClose,proto3,oneof"`
}

func (*ExecClientFrame_Start) isExecClientFrame_Frame() {}

func (*ExecClientFrame_Stdin) isExecClientFrame_Frame() {}

func (*ExecClientFrame_Resize) isExecClientFrame_Frame() {}

func (*ExecClientFrame_StdinClose) isExecClientFrame_Frame() {}

// ExecServerFrame is anything the daemon sends back. A session ends with
// exactly one exit frame.
type ExecServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ExecServerFrame_Stdout
	//	*ExecServerFrame_Stderr
	//	*ExecServerFrame_ExitCode
	Frame         isExecServerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecServerFrame) Reset() {
	*x = ExecServerFrame{}
	mi := &file_plbx_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecServerFrame) ProtoMessage() {}

func (x *ExecServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_plbx_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecServerFrame.ProtoReflect.Descriptor instead.
func (*ExecServerFrame) Descriptor() ([]byte, []int) {
	return file_plbx_proto_rawDescGZIP(), []int{40}
}

func (x *ExecServerFrame) GetFrame() isExecServerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ExecServerFrame) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Frame.(*ExecServerFrame_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecServerFrame) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Frame.(*ExecServerFrame_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecServerFrame) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Frame.(*ExecServerFrame_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isExecServerFrame_Frame interface {
	isExecServerFrame_Frame()
}

type ExecServerFrame_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecServerFrame_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecServerFrame_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*ExecServerFrame_Stdout) isExecServerFrame_Frame() {}

func (*ExecServerFrame_Stderr) isExecServerFrame_Frame() {}

func (*ExecServerFrame_ExitCode) isExecServerFrame_Frame() {}

var File_plbx_proto protoreflect.FileDescriptor

const file_plbx_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"plbx.proto\x12\aplbx.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x06Policy\x12\x16\n" +
	"\x06preset\x18\x01 \x01(\tR\x06preset\x12#\n" +
	"\x05rules\x18\x02 \x03(\v2\r.plbx.v1.RuleR\x05rules\"6\n" +
	"\x04Rule\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x14\n" +
	"\x05allow\x18\x02 \x01(\bR\x05allow\"\xbc\x01\n" +
	"\bDecision\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x18\n" +
	"\aallowed\x18\x05 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x18\n" +
	"\asandbox\x18\a \x01(\tR\asandbox\"U\n" +
	"\x0ePublishRequest\x12\x1e\n" +
	"\x03ref\x18\x01 \x01(\v2\f.plbx.v1.RefR\x03ref\x12#\n" +
	"\x05ports\x18\x02 \x03(\v2\r.plbx.v1.PortR\x05ports\"\x11\n" +
	"\x0fPublishResponse\"\x12\n" +
	"\x10GetPolicyRequest\"<\n" +
	"\x11GetPolicyResponse\x12'\n" +
	"\x06policy\x18\x01 \x01(\v2\x0f.plbx.v1.PolicyR\x06policy\";\n" +
	"\x10SetPolicyRequest\x12'\n" +
	"\x06policy\x18\x01 \x01(\v2\x0f.plbx.v1.PolicyR\x06policy\"\x13\n" +
	"\x11SetPolicyResponse\"*\n" +
	"\x12ConnectionsRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\x04R\x05since\"F\n" +
	"\x13ConnectionsResponse\x12/\n" +
	"\tdecisions\x18\x01 \x03(\v2\x11.plbx.v1.DecisionR\tdecisions\"\xe5\x02\n" +
	"\x04Spec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x122\n" +
	"\n" +
	"workspaces\x18\x04 \x03(\v2\x12.plbx.v1.WorkspaceR\n" +
	"workspaces\x120\n" +
	"\tresources\x18\x05 \x01(\v2\x12.plbx.v1.ResourcesR\tresources\x12(\n" +
	"\x03env\x18\x06 \x03(\v2\x16.plbx.v1.Spec.EnvEntryR\x03env\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05clone\x18\t \x01(\bR\x05clone\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\a\x10\b\"<\n" +
	"\tWorkspace\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1b\n" +
	"\tread_only\x18\x02 \x01(\bR\breadOnly\"7\n" +
	"\tResources\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\x01R\x04cpus\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x03R\x06memory\"^\n" +
	"\x04Port\x12\x12\n" +
	"\x04host\x18\x01 \x01(\x05R\x04host\x12\x18\n" +
	"\asandbox\x18\x02 \x01(\x05R\asandbox\x12\x14\n" +
	"\x05proto\x18\x03 \x01(\tR\x05proto\x12\x12\n" +
	"\x04bind\x18\x04 \x01(\tR\x04bind\"\x9a\x01\n" +
	"\x05State\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\"w\n" +
	"\aSandbox\x12!\n" +
	"\x04spec\x18\x01 \x01(\v2\r.plbx.v1.SpecR\x04spec\x12$\n" +
	"\x05state\x18\x02 \x01(\v2\x0e.plbx.v1.StateR\x05state\x12#\n" +
	"\x05ports\x18\x03 \x03(\v2\r.plbx.v1.PortR\x05ports\"-\n" +
	"\x03Ref\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"4\n" +
	"\x04Path\x12\x18\n" +
	"\asandbox\x18\x01 \x01(\tR\asandbox\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xea\x01\n" +
	"\vExecRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x03(\tR\x03cmd\x12/\n" +
	"\x03env\x18\x02 \x03(\v2\x1d.plbx.v1.ExecRequest.EnvEntryR\x03env\x12\x18\n" +
	"\aworkdir\x18\x03 \x01(\tR\aworkdir\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12 \n" +
	"\vinteractive\x18\x05 \x01(\bR\vinteractive\x12\x10\n" +
	"\x03tty\x18\x06 \x01(\bR\x03tty\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x06Sample\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12!\n" +
	"\fmemory_limit\x18\x03 \x01(\x03R\vmemoryLimit\".\n" +
	"\x04Size\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"2\n" +
	"\rCreateRequest\x12!\n" +
	"\x04spec\x18\x01 \x01(\v2\r.plbx.v1.SpecR\x04spec\"<\n" +
	"\x0eCreateResponse\x12*\n" +
	"\asandbox\x18\x01 \x01(\v2\x10.plbx.v1.SandboxR\asandbox\"\r\n" +
	"\vListRequest\">\n" +
	"\fListResponse\x12.\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x10.plbx.v1.SandboxR\tsandboxes\"0\n" +
	"\x0eInspectRequest\x12\x1e\n" +
	"\x03ref\x18\x01 \x01(\v2\f.plbx.v1.RefR\x03ref\"=\n" +
	"\x0fInspectResponse\x12*\n" +
	"\asandbox\x18\x01 \x01(\v2\x10.plbx.v1.SandboxR\asandbox\".\n" +
	"\fStartRequest\x12\x1e\n" +
	"\x03ref\x18\x01 \x01(\v2\f.plbx.v1.RefR\x03ref\"\x0f\n" +
	"\rStartResponse\"-\n" +
	"\vStopRequest\x12\x1e\n" +
	"\x03ref\x18\x01 \x01(\v2\f.plbx.v1.RefR\x03ref\"\x0e\n" +
	"\fStopResponse\"E\n" +
	"\rRemoveRequest\x12\x1e\n" +
	"\x03ref\x18\x01 \x01(\v2\f.plbx.v1.RefR\x03ref\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x10\n" +
	"\x0eRemoveResponse\"O\n" +
	"\vCopyRequest\x12\x1f\n" +
	"\x03src\x18\x01 \x01(\v2\r.plbx.v1.PathR\x03src\x12\x1f\n" +
	"\x03dst\x18\x02 \x01(\v2\r.plbx.v1.PathR\x03dst\"\x0e\n" +
	"\fCopyResponse\".\n" +
	"\fStatsRequest\x12\x1e\n" +
	"\x03ref\x18\x01 \x01(\v2\f.plbx.v1.RefR\x03ref\"~\n" +
	"\tExecStart\x12\x1e\n" +
	"\x03ref\x18\x01 \x01(\v2\f.plbx.v1.RefR\x03ref\x12.\n" +
	"\arequest\x18\x02 \x01(\v2\x14.plbx.v1.ExecRequestR\arequest\x12!\n" +
	"\x04size\x18\x03 \x01(\v2\r.plbx.v1.SizeR\x04size\"\x10\n" +
	"\x0eExecStdinClose\"\xc3\x01\n" +
	"\x0fExecClientFrame\x12*\n" +
	"\x05start\x18\x01 \x01(\v2\x12.plbx.v1.ExecStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12'\n" +
	"\x06resize\x18\x03 \x01(\v2\r.plbx.v1.SizeH\x00R\x06resize\x12:\n" +
	"\vstdin_close\x18\x04 \x01(\v2\x17.plbx.v1.ExecStdinCloseH\x00R\n" +
	"stdinCloseB\a\n" +
	"\x05frame\"m\n" +
	"\x0fExecServerFrame\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCodeB\a\n" +
	"\x05frame2\x99\x06\n" +
	"\tSandboxes\x129\n" +
	"\x06Create\x12\x16.plbx.v1.CreateRequest\x1a\x17.plbx.v1.CreateResponse\x123\n" +
	"\x04List\x12\x14.plbx.v1.ListRequest\x1a\x15.plbx.v1.ListResponse\x12<\n" +
	"\aInspect\x12\x17.plbx.v1.InspectRequest\x1a\x18.plbx.v1.InspectResponse\x126\n" +
	"\x05Start\x12\x15.plbx.v1.StartRequest\x1a\x16.plbx.v1.StartResponse\x123\n" +
	"\x04Stop\x12\x14.plbx.v1.StopRequest\x1a\x15.plbx.v1.StopResponse\x129\n" +
	"\x06Remove\x12\x16.plbx.v1.RemoveRequest\x1a\x17.plbx.v1.RemoveResponse\x123\n" +
	"\x04Copy\x12\x14.plbx.v1.CopyRequest\x1a\x15.plbx.v1.CopyResponse\x12<\n" +
	"\aPublish\x12\x17.plbx.v1.PublishRequest\x1a\x18.plbx.v1.PublishResponse\x121\n" +
	"\x05Stats\x12\x15.plbx.v1.StatsRequest\x1a\x0f.plbx.v1.Sample0\x01\x12>\n" +
	"\x04Exec\x12\x18.plbx.v1.ExecClientFrame\x1a\x18.plbx.v1.ExecServerFrame(\x010\x01\x12B\n" +
	"\tGetPolicy\x12\x19.plbx.v1.GetPolicyRequest\x1a\x1a.plbx.v1.GetPolicyResponse\x12B\n" +
	"\tSetPolicy\x12\x19.plbx.v1.SetPolicyRequest\x1a\x1a.plbx.v1.SetPolicyResponse\x12H\n" +
	"\vConnections\x12\x1b.plbx.v1.ConnectionsRequest\x1a\x1c.plbx.v1.ConnectionsResponseB;Z9github.com/rhizomatous/planterbox/internal/api/rpc/plbxv1b\x06proto3"

var (
	file_plbx_proto_rawDescOnce sync.Once
	file_plbx_proto_rawDescData []byte
)

func file_plbx_proto_rawDescGZIP() []byte {
	file_plbx_proto_rawDescOnce.Do(func() {
		file_plbx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plbx_proto_rawDesc), len(file_plbx_proto_rawDesc)))
	})
	return file_plbx_proto_rawDescData
}

var file_plbx_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_plbx_proto_goTypes = []any{
	(*Policy)(nil),                // 0: plbx.v1.Policy
	(*Rule)(nil),                  // 1: plbx.v1.Rule
	(*Decision)(nil),              // 2: plbx.v1.Decision
	(*PublishRequest)(nil),        // 3: plbx.v1.PublishRequest
	(*PublishResponse)(nil),       // 4: plbx.v1.PublishResponse
	(*GetPolicyRequest)(nil),      // 5: plbx.v1.GetPolicyRequest
	(*GetPolicyResponse)(nil),     // 6: plbx.v1.GetPolicyResponse
	(*SetPolicyRequest)(nil),      // 7: plbx.v1.SetPolicyRequest
	(*SetPolicyResponse)(nil),     // 8: plbx.v1.SetPolicyResponse
	(*ConnectionsRequest)(nil),    // 9: plbx.v1.ConnectionsRequest
	(*ConnectionsResponse)(nil),   // 10: plbx.v1.ConnectionsResponse
	(*Spec)(nil),                  // 11: plbx.v1.Spec
	(*Workspace)(nil),             // 12: plbx.v1.Workspace
	(*Resources)(nil),             // 13: plbx.v1.Resources
	(*Port)(nil),                  // 14: plbx.v1.Port
	(*State)(nil),                 // 15: plbx.v1.State
	(*Sandbox)(nil),               // 16: plbx.v1.Sandbox
	(*Ref)(nil),                   // 17: plbx.v1.Ref
	(*Path)(nil),                  // 18: plbx.v1.Path
	(*ExecRequest)(nil),           // 19: plbx.v1.ExecRequest
	(*Sample)(nil),                // 20: plbx.v1.Sample
	(*Size)(nil),                  // 21: plbx.v1.Size
	(*CreateRequest)(nil),         // 22: plbx.v1.CreateRequest
	(*CreateResponse)(nil),        // 23: plbx.v1.CreateResponse
	(*ListRequest)(nil),           // 24: plbx.v1.ListRequest
	(*ListResponse)(nil),          // 25: plbx.v1.ListResponse
	(*InspectRequest)(nil),        // 26: plbx.v1.InspectRequest
	(*InspectResponse)(nil),       // 27: plbx.v1.InspectResponse
	(*StartRequest)(nil),          // 28: plbx.v1.StartRequest
	(*StartResponse)(nil),         // 29: plbx.v1.StartResponse
	(*StopRequest)(nil),           // 30: plbx.v1.StopRequest
	(*StopResponse)(nil),          // 31: plbx.v1.StopResponse
	(*RemoveRequest)(nil),         // 32: plbx.v1.RemoveRequest
	(*RemoveResponse)(nil),        // 33: plbx.v1.RemoveResponse
	(*CopyRequest)(nil),           // 34: plbx.v1.CopyRequest
	(*CopyResponse)(nil),          // 35: plbx.v1.CopyResponse
	(*StatsRequest)(nil),          // 36: plbx.v1.StatsRequest
	(*ExecStart)(nil),             // 37: plbx.v1.ExecStart
	(*ExecStdinClose)(nil),        // 38: plbx.v1.ExecStdinClose
	(*ExecClientFrame)(nil),       // 39: plbx.v1.ExecClientFrame
	(*ExecServerFrame)(nil),       // 40: plbx.v1.ExecServerFrame
	nil,                           // 41: plbx.v1.Spec.EnvEntry
	nil,                           // 42: plbx.v1.ExecRequest.EnvEntry
	(*timestamppb.Timestamp)(nil), // 43: google.protobuf.Timestamp
}
var file_plbx_proto_depIdxs = []int32{
	1,  // 0: plbx.v1.Policy.rules:type_name -> plbx.v1.Rule
	43, // 1: plbx.v1.Decision.at:type_name -> google.protobuf.Timestamp
	17, // 2: plbx.v1.PublishRequest.ref:type_name -> plbx.v1.Ref
	14, // 3: plbx.v1.PublishRequest.ports:type_name -> plbx.v1.Port
	0,  // 4: plbx.v1.GetPolicyResponse.policy:type_name -> plbx.v1.Policy
	0,  // 5: plbx.v1.SetPolicyRequest.policy:type_name -> plbx.v1.Policy
	2,  // 6: plbx.v1.ConnectionsResponse.decisions:type_name -> plbx.v1.Decision
	12, // 7: plbx.v1.Spec.workspaces:type_name -> plbx.v1.Workspace
	13, // 8: plbx.v1.Spec.resources:type_name -> plbx.v1.Resources
	41, // 9: plbx.v1.Spec.env:type_name -> plbx.v1.Spec.EnvEntry
	43, // 10: plbx.v1.Spec.created_at:type_name -> google.protobuf.Timestamp
	43, // 11: plbx.v1.State.started_at:type_name -> google.protobuf.Timestamp
	11, // 12: plbx.v1.Sandbox.spec:type_name -> plbx.v1.Spec
	15, // 13: plbx.v1.Sandbox.state:type_name -> plbx.v1.State
	14, // 14: plbx.v1.Sandbox.ports:type_name -> plbx.v1.Port
	42, // 15: plbx.v1.ExecRequest.env:type_name -> plbx.v1.ExecRequest.EnvEntry
	11, // 16: plbx.v1.CreateRequest.spec:type_name -> plbx.v1.Spec
	16, // 17: plbx.v1.CreateResponse.sandbox:type_name -> plbx.v1.Sandbox
	16, // 18: plbx.v1.ListResponse.sandboxes:type_name -> plbx.v1.Sandbox
	17, // 19: plbx.v1.InspectRequest.ref:type_name -> plbx.v1.Ref
	16, // 20: plbx.v1.InspectResponse.sandbox:type_name -> plbx.v1.Sandbox
	17, // 21: plbx.v1.StartRequest.ref:type_name -> plbx.v1.Ref
	17, // 22: plbx.v1.StopRequest.ref:type_name -> plbx.v1.Ref
	17, // 23: plbx.v1.RemoveRequest.ref:type_name -> plbx.v1.Ref
	18, // 24: plbx.v1.CopyRequest.src:type_name -> plbx.v1.Path
	18, // 25: plbx.v1.CopyRequest.dst:type_name -> plbx.v1.Path
	17, // 26: plbx.v1.StatsRequest.ref:type_name -> plbx.v1.Ref
	17, // 27: plbx.v1.ExecStart.ref:type_name -> plbx.v1.Ref
	19, // 28: plbx.v1.ExecStart.request:type_name -> plbx.v1.ExecRequest
	21, // 29: plbx.v1.ExecStart.size:type_name -> plbx.v1.Size
	37, // 30: plbx.v1.ExecClientFrame.start:type_name -> plbx.v1.ExecStart
	21, // 31: plbx.v1.ExecClientFrame.resize:type_name -> plbx.v1.Size
	38, // 32: plbx.v1.ExecClientFrame.stdin_close:type_name -> plbx.v1.ExecStdinClose
	22, // 33: plbx.v1.Sandboxes.Create:input_type -> plbx.v1.CreateRequest
	24, // 34: plbx.v1.Sandboxes.List:input_type -> plbx.v1.ListRequest
	26, // 35: plbx.v1.Sandboxes.Inspect:input_type -> plbx.v1.InspectRequest
	28, // 36: plbx.v1.Sandboxes.Start:input_type -> plbx.v1.StartRequest
	30, // 37: plbx.v1.Sandboxes.Stop:input_type -> plbx.v1.StopRequest
	32, // 38: plbx.v1.Sandboxes.Remove:input_type -> plbx.v1.RemoveRequest
	34, // 39: plbx.v1.Sandboxes.Copy:input_type -> plbx.v1.CopyRequest
	3,  // 40: plbx.v1.Sandboxes.Publish:input_type -> plbx.v1.PublishRequest
	36, // 41: plbx.v1.Sandboxes.Stats:input_type -> plbx.v1.StatsRequest
	39, // 42: plbx.v1.Sandboxes.Exec:input_type -> plbx.v1.ExecClientFrame
	5,  // 43: plbx.v1.Sandboxes.GetPolicy:input_type -> plbx.v1.GetPolicyRequest
	7,  // 44: plbx.v1.Sandboxes.SetPolicy:input_type -> plbx.v1.SetPolicyRequest
	9,  // 45: plbx.v1.Sandboxes.Connections:input_type -> plbx.v1.ConnectionsRequest
	23, // 46: plbx.v1.Sandboxes.Create:output_type -> plbx.v1.CreateResponse
	25, // 47: plbx.v1.Sandboxes.List:output_type -> plbx.v1.ListResponse
	27, // 48: plbx.v1.Sandboxes.Inspect:output_type -> plbx.v1.InspectResponse
	29, // 49: plbx.v1.Sandboxes.Start:output_type -> plbx.v1.StartResponse
	31, // 50: plbx.v1.Sandboxes.Stop:output_type -> plbx.v1.StopResponse
	33, // 51: plbx.v1.Sandboxes.Remove:output_type -> plbx.v1.RemoveResponse
	35, // 52: plbx.v1.Sandboxes.Copy:output_type -> plbx.v1.CopyResponse
	4,  // 53: plbx.v1.Sandboxes.Publish:output_type -> plbx.v1.PublishResponse
	20, // 54: plbx.v1.Sandboxes.Stats:output_type -> plbx.v1.Sample
	40, // 55: plbx.v1.Sandboxes.Exec:output_type -> plbx.v1.ExecServerFrame
	6,  // 56: plbx.v1.Sandboxes.GetPolicy:output_type -> plbx.v1.GetPolicyResponse
	8,  // 57: plbx.v1.Sandboxes.SetPolicy:output_type -> plbx.v1.SetPolicyResponse
	10, // 58: plbx.v1.Sandboxes.Connections:output_type -> plbx.v1.ConnectionsResponse
	46, // [46:59] is the sub-list for method output_type
	33, // [33:46] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_plbx_proto_init() }
func file_plbx_proto_init() {
	if File_plbx_proto != nil {
		return
	}
	file_plbx_proto_msgTypes[39].OneofWrappers = []any{
		(*ExecClientFrame_Start)(nil),
		(*ExecClientFrame_Stdin)(nil),
		(*ExecClientFrame_Resize)(nil),
		(*ExecClientFrame_StdinClose)(nil),
	}
	file_plbx_proto_msgTypes[40].OneofWrappers = []any{
		(*ExecServerFrame_Stdout)(nil),
		(*ExecServerFrame_Stderr)(nil),
		(*ExecServerFrame_ExitCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plbx_proto_rawDesc), len(file_plbx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plbx_proto_goTypes,
		DependencyIndexes: file_plbx_proto_depIdxs,
		MessageInfos:      file_plbx_proto_msgTypes,
	}.Build()
	File_plbx_proto = out.File
	file_plbx_proto_goTypes = nil
	file_plbx_proto_depIdxs = nil
}
