// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: plbx.proto

package plbxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sandboxes_Create_FullMethodName      = "/plbx.v1.Sandboxes/Create"
	Sandboxes_List_FullMethodName        = "/plbx.v1.Sandboxes/List"
	Sandboxes_Inspect_FullMethodName     = "/plbx.v1.Sandboxes/Inspect"
	Sandboxes_Start_FullMethodName       = "/plbx.v1.Sandboxes/Start"
	Sandboxes_Stop_FullMethodName        = "/plbx.v1.Sandboxes/Stop"
	Sandboxes_Remove_FullMethodName      = "/plbx.v1.Sandboxes/Remove"
	Sandboxes_Copy_FullMethodName        = "/plbx.v1.Sandboxes/Copy"
	Sandboxes_Publish_FullMethodName     = "/plbx.v1.Sandboxes/Publish"
	Sandboxes_Stats_FullMethodName       = "/plbx.v1.Sandboxes/Stats"
	Sandboxes_PullImage_FullMethodName   = "/plbx.v1.Sandboxes/PullImage"
	Sandboxes_Exec_FullMethodName        = "/plbx.v1.Sandboxes/Exec"
	Sandboxes_GetPolicy_FullMethodName   = "/plbx.v1.Sandboxes/GetPolicy"
	Sandboxes_SetPolicy_FullMethodName   = "/plbx.v1.Sandboxes/SetPolicy"
	Sandboxes_Connections_FullMethodName = "/plbx.v1.Sandboxes/Connections"
	Sandboxes_Info_FullMethodName        = "/plbx.v1.Sandboxes/Info"
)

// SandboxesClient is the client API for Sandboxes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sandboxes is the daemon's half of api.Service. Every method mirrors one, so
// the in-process and over-the-socket implementations stay in step.
//
// Errors travel as gRPC status codes and are mapped back to the api package's
// sentinels on the client, so errors.Is keeps working across the socket.
type SandboxesClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// Stats streams samples until the sandbox stops or the client goes away.
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Sample], error)
	// PullImage fetches an image, streaming the runtime's own progress. An
	// image already present streams nothing and ends at once.
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullProgress], error)
	// Exec runs a command in a sandbox with its stdio streamed both ways. The
	// client's first frame must be a Start; the daemon owns the session, which
	// is what lets it hold a pty and what the SSH gateway will attach to.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecClientFrame, ExecServerFrame], error)
	GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*GetPolicyResponse, error)
	SetPolicy(ctx context.Context, in *SetPolicyRequest, opts ...grpc.CallOption) (*SetPolicyResponse, error)
	// Connections returns what the proxy decided, newer than a sequence the
	// caller already has. Polled rather than streamed: the dashboard re-reads on
	// a tick anyway, and this costs the daemon no subscription per viewer.
	Connections(ctx context.Context, in *ConnectionsRequest, opts ...grpc.CallOption) (*ConnectionsResponse, error)
	// Info reports what the daemon is, so a client can tell whether it is
	// talking to its own build. plbx autostarts plbxd and the daemon outlives
	// an upgrade, so the two silently disagreeing about behaviour is the
	// normal outcome of installing a new version, not an exotic one.
	//
	// Not part of api.Service: there is no daemon in the in-process case, so
	// there is nothing for it to answer.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type sandboxesClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxesClient(cc grpc.ClientConnInterface) SandboxesClient {
	return &sandboxesClient{cc}
}

func (c *sandboxesClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, Sandboxes_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxesClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, Sandboxes_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxesClient) Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectResponse)
	err := c.cc.Invoke(ctx, Sandboxes_Inspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxesClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, Sandboxes_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxesClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, Sandboxes_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxesClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, Sandboxes_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxesClient) Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyResponse)
	err := c.cc.Invoke(ctx, Sandboxes_Copy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxesClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, Sandboxes_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxesClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Sample], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandboxes_ServiceDesc.Streams[0], Sandboxes_Stats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatsRequest, Sample]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandboxes_StatsClient = grpc.ServerStreamingClient[Sample]

func (c *sandboxesClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PullProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandboxes_ServiceDesc.Streams[1], Sandboxes_PullImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullImageRequest, PullProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandboxes_PullImageClient = grpc.ServerStreamingClient[PullProgress]

func (c *sandboxesClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecClientFrame, ExecServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sandboxes_ServiceDesc.Streams[2], Sandboxes_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecClientFrame, ExecServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandboxes_ExecClient = grpc.BidiStreamingClient[ExecClientFrame, ExecServerFrame]

func (c *sandboxesClient) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*GetPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPolicyResponse)
	err := c.cc.Invoke(ctx, Sandboxes_GetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxesClient) SetPolicy(ctx context.Context, in *SetPolicyRequest, opts ...grpc.CallOption) (*SetPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPolicyResponse)
	err := c.cc.Invoke(ctx, Sandboxes_SetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxesClient) Connections(ctx context.Context, in *ConnectionsRequest, opts ...grpc.CallOption) (*ConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionsResponse)
	err := c.cc.Invoke(ctx, Sandboxes_Connections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxesClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, Sandboxes_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxesServer is the server API for Sandboxes service.
// All implementations must embed UnimplementedSandboxesServer
// for forward compatibility.
//
// Sandboxes is the daemon's half of api.Service. Every method mirrors one, so
// the in-process and over-the-socket implementations stay in step.
//
// Errors travel as gRPC status codes and are mapped back to the api package's
// sentinels on the client, so errors.Is keeps working across the socket.
type SandboxesServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Inspect(context.Context, *InspectRequest) (*InspectResponse, error)
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	Copy(context.Context, *CopyRequest) (*CopyResponse, error)
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// Stats streams samples until the sandbox stops or the client goes away.
	Stats(*StatsRequest, grpc.ServerStreamingServer[Sample]) error
	// PullImage fetches an image, streaming the runtime's own progress. An
	// image already present streams nothing and ends at once.
	PullImage(*PullImageRequest, grpc.ServerStreamingServer[PullProgress]) error
	// Exec runs a command in a sandbox with its stdio streamed both ways. The
	// client's first frame must be a Start; the daemon owns the session, which
	// is what lets it hold a pty and what the SSH gateway will attach to.
	Exec(grpc.BidiStreamingServer[ExecClientFrame, ExecServerFrame]) error
	GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error)
	SetPolicy(context.Context, *SetPolicyRequest) (*SetPolicyResponse, error)
	// Connections returns what the proxy decided, newer than a sequence the
	// caller already has. Polled rather than streamed: the dashboard re-reads on
	// a tick anyway, and this costs the daemon no subscription per viewer.
	Connections(context.Context, *ConnectionsRequest) (*ConnectionsResponse, error)
	// Info reports what the daemon is, so a client can tell whether it is
	// talking to its own build. plbx autostarts plbxd and the daemon outlives
	// an upgrade, so the two silently disagreeing about behaviour is the
	// normal outcome of installing a new version, not an exotic one.
	//
	// Not part of api.Service: there is no daemon in the in-process case, so
	// there is nothing for it to answer.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	mustEmbedUnimplementedSandboxesServer()
}

// UnimplementedSandboxesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxesServer struct{}

func (UnimplementedSandboxesServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSandboxesServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSandboxesServer) Inspect(context.Context, *InspectRequest) (*InspectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Inspect not implemented")
}
func (UnimplementedSandboxesServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedSandboxesServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedSandboxesServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedSandboxesServer) Copy(context.Context, *CopyRequest) (*CopyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Copy not implemented")
}
func (UnimplementedSandboxesServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedSandboxesServer) Stats(*StatsRequest, grpc.ServerStreamingServer[Sample]) error {
	return status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedSandboxesServer) PullImage(*PullImageRequest, grpc.ServerStreamingServer[PullProgress]) error {
	return status.Error(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedSandboxesServer) Exec(grpc.BidiStreamingServer[ExecClientFrame, ExecServerFrame]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxesServer) GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedSandboxesServer) SetPolicy(context.Context, *SetPolicyRequest) (*SetPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPolicy not implemented")
}
func (UnimplementedSandboxesServer) Connections(context.Context, *ConnectionsRequest) (*ConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connections not implemented")
}
func (UnimplementedSandboxesServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedSandboxesServer) mustEmbedUnimplementedSandboxesServer() {}
func (UnimplementedSandboxesServer) testEmbeddedByValue()                   {}

// UnsafeSandboxesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxesServer will
// result in compilation errors.
type UnsafeSandboxesServer interface {
	mustEmbedUnimplementedSandboxesServer()
}

func RegisterSandboxesServer(s grpc.ServiceRegistrar, srv SandboxesServer) {
	// If the following call panics, it indicates UnimplementedSandboxesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sandboxes_ServiceDesc, srv)
}

func _Sandboxes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandboxes_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandboxes_Inspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).Inspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_Inspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).Inspect(ctx, req.(*InspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandboxes_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandboxes_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandboxes_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandboxes_Copy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).Copy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_Copy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).Copy(ctx, req.(*CopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandboxes_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandboxes_Stats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxesServer).Stats(m, &grpc.GenericServerStream[StatsRequest, Sample]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandboxes_StatsServer = grpc.ServerStreamingServer[Sample]

func _Sandboxes_PullImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxesServer).PullImage(m, &grpc.GenericServerStream[PullImageRequest, PullProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandboxes_PullImageServer = grpc.ServerStreamingServer[PullProgress]

func _Sandboxes_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxesServer).Exec(&grpc.GenericServerStream[ExecClientFrame, ExecServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sandboxes_ExecServer = grpc.BidiStreamingServer[ExecClientFrame, ExecServerFrame]

func _Sandboxes_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).GetPolicy(ctx, req.(*GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandboxes_SetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).SetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_SetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).SetPolicy(ctx, req.(*SetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandboxes_Connections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).Connections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_Connections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).Connections(ctx, req.(*ConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sandboxes_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxesServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sandboxes_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxesServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sandboxes_ServiceDesc is the grpc.ServiceDesc for Sandboxes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sandboxes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plbx.v1.Sandboxes",
	HandlerType: (*SandboxesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Sandboxes_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Sandboxes_List_Handler,
		},
		{
			MethodName: "Inspect",
			Handler:    _Sandboxes_Inspect_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Sandboxes_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Sandboxes_Stop_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Sandboxes_Remove_Handler,
		},
		{
			MethodName: "Copy",
			Handler:    _Sandboxes_Copy_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _Sandboxes_Publish_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _Sandboxes_GetPolicy_Handler,
		},
		{
			MethodName: "SetPolicy",
			Handler:    _Sandboxes_SetPolicy_Handler,
		},
		{
			MethodName: "Connections",
			Handler:    _Sandboxes_Connections_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Sandboxes_Info_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stats",
			Handler:       _Sandboxes_Stats_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PullImage",
			Handler:       _Sandboxes_PullImage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _Sandboxes_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plbx.proto",
}
